import mongoose from 'mongoose';

const orderSchema = new mongoose.Schema(
    {
        shippingDetails:{
            address:{
                type:String,
                required:true,
            },
            city:{
                type:String,
                required:true
            },
            state:{
                type:String,
                required:true
            },
            country:{
                type:String,
                required:true
            },
            pinCode:{
                type:Number,
                required:true
            },
            phoneNo:{
                type:Number,
                required:true
            }
        },
        orderDetails:[
            {
                name:{
                    type:String,
                    required:true
                },
                price:{
                    type:Number,
                    required:true
                },
                quantity:{
                    type:Number,
                    required:true
                },
                status:{
                    type:String,
                    required:true
                },
                product:{
                    type:mongoose.Schema.objectId,
                    ref:"products",
                    required:true
                }
            },
        ],
        user:{
            type:mongoose.Schema.ObjectId,
            ref:"users",
            required:true
        },
        paymentDetails:{
            paymentId:{
                type:String,
                required:true
            },
            paymentStatus:{
                type:Sting,
                required:true
            }
        },
        OrderStatus:{
            type:String,
            required:true,
            default:"Not yet dispatch"
        },
        itemPrice:{
            type:Number,
            required:true
        },
        taxPrice:{
            type:Number,
            required:true
        },
        shippingPrice:{
            type:Number,
            required:true
        },
        totalPrice:{
            type:Number,
            required:true
        },
        orderedDate:{
            type:Date,
            required:true
        },
        deliveredAt:{
            type:Date,
        }
    },
    {
        timestamps:true
    }
);

export const OrderModel = mongoose.model("orders",orderSchema);